// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games(id, map_index, winner_id, duration_seconds)
VALUES ($1,
        $2,
        $3,
        $4)
RETURNING id, map_index, winner_id, duration_seconds, played_at
`

type CreateGameParams struct {
	ID              uuid.UUID
	MapIndex        int32
	WinnerID        uuid.NullUUID
	DurationSeconds int32
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.ID,
		arg.MapIndex,
		arg.WinnerID,
		arg.DurationSeconds,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.MapIndex,
		&i.WinnerID,
		&i.DurationSeconds,
		&i.PlayedAt,
	)
	return i, err
}

const createGamePlayer = `-- name: CreateGamePlayer :one
INSERT INTO game_users(game_id, user_id, hidden_seconds, ranking)
VALUES (
        $1,
        $2,
        $3,
        $4
       )
RETURNING game_id, user_id, hidden_seconds, ranking
`

type CreateGamePlayerParams struct {
	GameID        uuid.UUID
	UserID        uuid.UUID
	HiddenSeconds int32
	Ranking       int32
}

func (q *Queries) CreateGamePlayer(ctx context.Context, arg CreateGamePlayerParams) (GameUser, error) {
	row := q.db.QueryRowContext(ctx, createGamePlayer,
		arg.GameID,
		arg.UserID,
		arg.HiddenSeconds,
		arg.Ranking,
	)
	var i GameUser
	err := row.Scan(
		&i.GameID,
		&i.UserID,
		&i.HiddenSeconds,
		&i.Ranking,
	)
	return i, err
}
