// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID              uuid.UUID
	MapIndex        int32
	WinnerID        uuid.NullUUID
	DurationSeconds int32
	PlayedAt        time.Time
}

type GameUser struct {
	GameID        uuid.UUID
	UserID        uuid.UUID
	HiddenSeconds int32
	Ranking       int32
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Wins         int32
	Loses        int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
