// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions(user_id)
VALUES ($1 )
RETURNING token, user_id, expires_at
`

func (q *Queries) CreateSession(ctx context.Context, userID uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, userID)
	var i Session
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT token, user_id, expires_at FROM sessions WHERE token = $1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}
